/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ConnectionWorkflowSummary struct for ConnectionWorkflowSummary
type ConnectionWorkflowSummary struct {
	Name string `json:"name"`
	// User provided friendly workflow description
	Description *string `json:"description,omitempty"`
	// If true, this workflow cannot be edited or run directly by the user.
	Immutable *bool `json:"immutable,omitempty"`
	// The set of capabilities to enable for a connection
	Capabilities []ConnectionProviderCapability `json:"capabilities"`
}

// NewConnectionWorkflowSummary instantiates a new ConnectionWorkflowSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionWorkflowSummary(name string, capabilities []ConnectionProviderCapability) *ConnectionWorkflowSummary {
	this := ConnectionWorkflowSummary{}
	this.Name = name
	this.Capabilities = capabilities
	return &this
}

// NewConnectionWorkflowSummaryWithDefaults instantiates a new ConnectionWorkflowSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionWorkflowSummaryWithDefaults() *ConnectionWorkflowSummary {
	this := ConnectionWorkflowSummary{}
	return &this
}

// GetName returns the Name field value
func (o *ConnectionWorkflowSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConnectionWorkflowSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConnectionWorkflowSummary) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ConnectionWorkflowSummary) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionWorkflowSummary) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ConnectionWorkflowSummary) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ConnectionWorkflowSummary) SetDescription(v string) {
	o.Description = &v
}

// GetImmutable returns the Immutable field value if set, zero value otherwise.
func (o *ConnectionWorkflowSummary) GetImmutable() bool {
	if o == nil || o.Immutable == nil {
		var ret bool
		return ret
	}
	return *o.Immutable
}

// GetImmutableOk returns a tuple with the Immutable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectionWorkflowSummary) GetImmutableOk() (*bool, bool) {
	if o == nil || o.Immutable == nil {
		return nil, false
	}
	return o.Immutable, true
}

// HasImmutable returns a boolean if a field has been set.
func (o *ConnectionWorkflowSummary) HasImmutable() bool {
	if o != nil && o.Immutable != nil {
		return true
	}

	return false
}

// SetImmutable gets a reference to the given bool and assigns it to the Immutable field.
func (o *ConnectionWorkflowSummary) SetImmutable(v bool) {
	o.Immutable = &v
}

// GetCapabilities returns the Capabilities field value
func (o *ConnectionWorkflowSummary) GetCapabilities() []ConnectionProviderCapability {
	if o == nil {
		var ret []ConnectionProviderCapability
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
func (o *ConnectionWorkflowSummary) GetCapabilitiesOk() (*[]ConnectionProviderCapability, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Capabilities, true
}

// SetCapabilities sets field value
func (o *ConnectionWorkflowSummary) SetCapabilities(v []ConnectionProviderCapability) {
	o.Capabilities = v
}

func (o ConnectionWorkflowSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Immutable != nil {
		toSerialize["immutable"] = o.Immutable
	}
	if true {
		toSerialize["capabilities"] = o.Capabilities
	}
	return json.Marshal(toSerialize)
}

type NullableConnectionWorkflowSummary struct {
	value *ConnectionWorkflowSummary
	isSet bool
}

func (v NullableConnectionWorkflowSummary) Get() *ConnectionWorkflowSummary {
	return v.value
}

func (v *NullableConnectionWorkflowSummary) Set(val *ConnectionWorkflowSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionWorkflowSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionWorkflowSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionWorkflowSummary(val *ConnectionWorkflowSummary) *NullableConnectionWorkflowSummary {
	return &NullableConnectionWorkflowSummary{value: val, isSet: true}
}

func (v NullableConnectionWorkflowSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionWorkflowSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
