/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ContainerWorkflowStepAllOf An individual container workflow step
type ContainerWorkflowStepAllOf struct {
	// Type of step
	Type string `json:"type"`
}

// NewContainerWorkflowStepAllOf instantiates a new ContainerWorkflowStepAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerWorkflowStepAllOf(type_ string) *ContainerWorkflowStepAllOf {
	this := ContainerWorkflowStepAllOf{}
	this.Type = type_
	return &this
}

// NewContainerWorkflowStepAllOfWithDefaults instantiates a new ContainerWorkflowStepAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerWorkflowStepAllOfWithDefaults() *ContainerWorkflowStepAllOf {
	this := ContainerWorkflowStepAllOf{}
	return &this
}

// GetType returns the Type field value
func (o *ContainerWorkflowStepAllOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ContainerWorkflowStepAllOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ContainerWorkflowStepAllOf) SetType(v string) {
	o.Type = v
}

func (o ContainerWorkflowStepAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableContainerWorkflowStepAllOf struct {
	value *ContainerWorkflowStepAllOf
	isSet bool
}

func (v NullableContainerWorkflowStepAllOf) Get() *ContainerWorkflowStepAllOf {
	return v.value
}

func (v *NullableContainerWorkflowStepAllOf) Set(val *ContainerWorkflowStepAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerWorkflowStepAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerWorkflowStepAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerWorkflowStepAllOf(val *ContainerWorkflowStepAllOf) *NullableContainerWorkflowStepAllOf {
	return &NullableContainerWorkflowStepAllOf{value: val, isSet: true}
}

func (v NullableContainerWorkflowStepAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerWorkflowStepAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
