/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// WorkflowRevisionAllOf A point-in-time representation of the content of a yaml workflow definition
type WorkflowRevisionAllOf struct {
	// Time of creation
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// A parsed representation of the declared parameters in a workflow yaml file
	Parameters *map[string]WorkflowParameter `json:"parameters,omitempty"`
	// Raw YAML representation of the yaml
	Raw string `json:"raw"`
	// A list of parsed information about workflow steps
	Steps []WorkflowStep `json:"steps"`
	// The list of triggers defined in this revision
	Triggers []WorkflowTrigger `json:"triggers"`
}

// NewWorkflowRevisionAllOf instantiates a new WorkflowRevisionAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowRevisionAllOf(raw string, steps []WorkflowStep, triggers []WorkflowTrigger) *WorkflowRevisionAllOf {
	this := WorkflowRevisionAllOf{}
	this.Raw = raw
	this.Steps = steps
	this.Triggers = triggers
	return &this
}

// NewWorkflowRevisionAllOfWithDefaults instantiates a new WorkflowRevisionAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowRevisionAllOfWithDefaults() *WorkflowRevisionAllOf {
	this := WorkflowRevisionAllOf{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *WorkflowRevisionAllOf) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRevisionAllOf) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *WorkflowRevisionAllOf) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *WorkflowRevisionAllOf) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetParameters returns the Parameters field value if set, zero value otherwise.
func (o *WorkflowRevisionAllOf) GetParameters() map[string]WorkflowParameter {
	if o == nil || o.Parameters == nil {
		var ret map[string]WorkflowParameter
		return ret
	}
	return *o.Parameters
}

// GetParametersOk returns a tuple with the Parameters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRevisionAllOf) GetParametersOk() (*map[string]WorkflowParameter, bool) {
	if o == nil || o.Parameters == nil {
		return nil, false
	}
	return o.Parameters, true
}

// HasParameters returns a boolean if a field has been set.
func (o *WorkflowRevisionAllOf) HasParameters() bool {
	if o != nil && o.Parameters != nil {
		return true
	}

	return false
}

// SetParameters gets a reference to the given map[string]WorkflowParameter and assigns it to the Parameters field.
func (o *WorkflowRevisionAllOf) SetParameters(v map[string]WorkflowParameter) {
	o.Parameters = &v
}

// GetRaw returns the Raw field value
func (o *WorkflowRevisionAllOf) GetRaw() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Raw
}

// GetRawOk returns a tuple with the Raw field value
// and a boolean to check if the value has been set.
func (o *WorkflowRevisionAllOf) GetRawOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Raw, true
}

// SetRaw sets field value
func (o *WorkflowRevisionAllOf) SetRaw(v string) {
	o.Raw = v
}

// GetSteps returns the Steps field value
func (o *WorkflowRevisionAllOf) GetSteps() []WorkflowStep {
	if o == nil {
		var ret []WorkflowStep
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *WorkflowRevisionAllOf) GetStepsOk() ([]WorkflowStep, bool) {
	if o == nil {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *WorkflowRevisionAllOf) SetSteps(v []WorkflowStep) {
	o.Steps = v
}

// GetTriggers returns the Triggers field value
func (o *WorkflowRevisionAllOf) GetTriggers() []WorkflowTrigger {
	if o == nil {
		var ret []WorkflowTrigger
		return ret
	}

	return o.Triggers
}

// GetTriggersOk returns a tuple with the Triggers field value
// and a boolean to check if the value has been set.
func (o *WorkflowRevisionAllOf) GetTriggersOk() ([]WorkflowTrigger, bool) {
	if o == nil {
		return nil, false
	}
	return o.Triggers, true
}

// SetTriggers sets field value
func (o *WorkflowRevisionAllOf) SetTriggers(v []WorkflowTrigger) {
	o.Triggers = v
}

func (o WorkflowRevisionAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedAt != nil {
		toSerialize["created_at"] = o.CreatedAt
	}
	if o.Parameters != nil {
		toSerialize["parameters"] = o.Parameters
	}
	if true {
		toSerialize["raw"] = o.Raw
	}
	if true {
		toSerialize["steps"] = o.Steps
	}
	if true {
		toSerialize["triggers"] = o.Triggers
	}
	return json.Marshal(toSerialize)
}

type NullableWorkflowRevisionAllOf struct {
	value *WorkflowRevisionAllOf
	isSet bool
}

func (v NullableWorkflowRevisionAllOf) Get() *WorkflowRevisionAllOf {
	return v.value
}

func (v *NullableWorkflowRevisionAllOf) Set(val *WorkflowRevisionAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowRevisionAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowRevisionAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowRevisionAllOf(val *WorkflowRevisionAllOf) *NullableWorkflowRevisionAllOf {
	return &NullableWorkflowRevisionAllOf{value: val, isSet: true}
}

func (v NullableWorkflowRevisionAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowRevisionAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
