/*
 * Relay API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v20200615
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WorkflowsView An object containing an array of workflows
type WorkflowsView struct {
	// A list of workflows
	Workflows *[]WorkflowView `json:"workflows,omitempty"`
}

// NewWorkflowsView instantiates a new WorkflowsView object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowsView() *WorkflowsView {
	this := WorkflowsView{}
	return &this
}

// NewWorkflowsViewWithDefaults instantiates a new WorkflowsView object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowsViewWithDefaults() *WorkflowsView {
	this := WorkflowsView{}
	return &this
}

// GetWorkflows returns the Workflows field value if set, zero value otherwise.
func (o *WorkflowsView) GetWorkflows() []WorkflowView {
	if o == nil || o.Workflows == nil {
		var ret []WorkflowView
		return ret
	}
	return *o.Workflows
}

// GetWorkflowsOk returns a tuple with the Workflows field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowsView) GetWorkflowsOk() (*[]WorkflowView, bool) {
	if o == nil || o.Workflows == nil {
		return nil, false
	}
	return o.Workflows, true
}

// HasWorkflows returns a boolean if a field has been set.
func (o *WorkflowsView) HasWorkflows() bool {
	if o != nil && o.Workflows != nil {
		return true
	}

	return false
}

// SetWorkflows gets a reference to the given []WorkflowView and assigns it to the Workflows field.
func (o *WorkflowsView) SetWorkflows(v []WorkflowView) {
	o.Workflows = &v
}

func (o WorkflowsView) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Workflows != nil {
		toSerialize["workflows"] = o.Workflows
	}
	return json.Marshal(toSerialize)
}

type NullableWorkflowsView struct {
	value *WorkflowsView
	isSet bool
}

func (v NullableWorkflowsView) Get() *WorkflowsView {
	return v.value
}

func (v *NullableWorkflowsView) Set(val *WorkflowsView) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowsView) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowsView) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowsView(val *WorkflowsView) *NullableWorkflowsView {
	return &NullableWorkflowsView{value: val, isSet: true}
}

func (v NullableWorkflowsView) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowsView) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


