/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PostAccountContacts200Response Success response
type PostAccountContacts200Response struct {
	// Did this succeed?
	Success *bool `json:"success,omitempty"`
}

// NewPostAccountContacts200Response instantiates a new PostAccountContacts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostAccountContacts200Response() *PostAccountContacts200Response {
	this := PostAccountContacts200Response{}
	return &this
}

// NewPostAccountContacts200ResponseWithDefaults instantiates a new PostAccountContacts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostAccountContacts200ResponseWithDefaults() *PostAccountContacts200Response {
	this := PostAccountContacts200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *PostAccountContacts200Response) GetSuccess() bool {
	if o == nil || o.Success == nil {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostAccountContacts200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || o.Success == nil {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *PostAccountContacts200Response) HasSuccess() bool {
	if o != nil && o.Success != nil {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *PostAccountContacts200Response) SetSuccess(v bool) {
	o.Success = &v
}

func (o PostAccountContacts200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullablePostAccountContacts200Response struct {
	value *PostAccountContacts200Response
	isSet bool
}

func (v NullablePostAccountContacts200Response) Get() *PostAccountContacts200Response {
	return v.value
}

func (v *NullablePostAccountContacts200Response) Set(val *PostAccountContacts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAccountContacts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAccountContacts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAccountContacts200Response(val *PostAccountContacts200Response) *NullablePostAccountContacts200Response {
	return &NullablePostAccountContacts200Response{value: val, isSet: true}
}

func (v NullablePostAccountContacts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAccountContacts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
