/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetUsers200Response The response type for the list of account users
type GetUsers200Response struct {
	// The list of users in this account
	Users []User `json:"users,omitempty"`
}

// NewGetUsers200Response instantiates a new GetUsers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUsers200Response() *GetUsers200Response {
	this := GetUsers200Response{}
	return &this
}

// NewGetUsers200ResponseWithDefaults instantiates a new GetUsers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUsers200ResponseWithDefaults() *GetUsers200Response {
	this := GetUsers200Response{}
	return &this
}

// GetUsers returns the Users field value if set, zero value otherwise.
func (o *GetUsers200Response) GetUsers() []User {
	if o == nil || o.Users == nil {
		var ret []User
		return ret
	}
	return o.Users
}

// GetUsersOk returns a tuple with the Users field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUsers200Response) GetUsersOk() ([]User, bool) {
	if o == nil || o.Users == nil {
		return nil, false
	}
	return o.Users, true
}

// HasUsers returns a boolean if a field has been set.
func (o *GetUsers200Response) HasUsers() bool {
	if o != nil && o.Users != nil {
		return true
	}

	return false
}

// SetUsers gets a reference to the given []User and assigns it to the Users field.
func (o *GetUsers200Response) SetUsers(v []User) {
	o.Users = v
}

func (o GetUsers200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Users != nil {
		toSerialize["users"] = o.Users
	}
	return json.Marshal(toSerialize)
}

type NullableGetUsers200Response struct {
	value *GetUsers200Response
	isSet bool
}

func (v NullableGetUsers200Response) Get() *GetUsers200Response {
	return v.value
}

func (v *NullableGetUsers200Response) Set(val *GetUsers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUsers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUsers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUsers200Response(val *GetUsers200Response) *NullableGetUsers200Response {
	return &NullableGetUsers200Response{value: val, isSet: true}
}

func (v NullableGetUsers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUsers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
