/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EventIdentifier A unique identifier for an event
type EventIdentifier struct {
	// The unique identifier of this event
	Id string `json:"id"`
}

// NewEventIdentifier instantiates a new EventIdentifier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEventIdentifier(id string) *EventIdentifier {
	this := EventIdentifier{}
	this.Id = id
	return &this
}

// NewEventIdentifierWithDefaults instantiates a new EventIdentifier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEventIdentifierWithDefaults() *EventIdentifier {
	this := EventIdentifier{}
	return &this
}

// GetId returns the Id field value
func (o *EventIdentifier) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EventIdentifier) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EventIdentifier) SetId(v string) {
	o.Id = v
}

func (o EventIdentifier) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableEventIdentifier struct {
	value *EventIdentifier
	isSet bool
}

func (v NullableEventIdentifier) Get() *EventIdentifier {
	return v.value
}

func (v *NullableEventIdentifier) Set(val *EventIdentifier) {
	v.value = val
	v.isSet = true
}

func (v NullableEventIdentifier) IsSet() bool {
	return v.isSet
}

func (v *NullableEventIdentifier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventIdentifier(val *EventIdentifier) *NullableEventIdentifier {
	return &NullableEventIdentifier{value: val, isSet: true}
}

func (v NullableEventIdentifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventIdentifier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
