/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WorkflowRunSummaryAllOf A summary of a workflow run
type WorkflowRunSummaryAllOf struct {
	CreatedBy *WorkflowRunCreator        `json:"created_by,omitempty"`
	Revision  WorkflowRevisionIdentifier `json:"revision"`
	State     WorkflowRunStateSummary    `json:"state"`
}

// NewWorkflowRunSummaryAllOf instantiates a new WorkflowRunSummaryAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowRunSummaryAllOf(revision WorkflowRevisionIdentifier, state WorkflowRunStateSummary) *WorkflowRunSummaryAllOf {
	this := WorkflowRunSummaryAllOf{}
	this.Revision = revision
	this.State = state
	return &this
}

// NewWorkflowRunSummaryAllOfWithDefaults instantiates a new WorkflowRunSummaryAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowRunSummaryAllOfWithDefaults() *WorkflowRunSummaryAllOf {
	this := WorkflowRunSummaryAllOf{}
	return &this
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *WorkflowRunSummaryAllOf) GetCreatedBy() WorkflowRunCreator {
	if o == nil || o.CreatedBy == nil {
		var ret WorkflowRunCreator
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRunSummaryAllOf) GetCreatedByOk() (*WorkflowRunCreator, bool) {
	if o == nil || o.CreatedBy == nil {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *WorkflowRunSummaryAllOf) HasCreatedBy() bool {
	if o != nil && o.CreatedBy != nil {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given WorkflowRunCreator and assigns it to the CreatedBy field.
func (o *WorkflowRunSummaryAllOf) SetCreatedBy(v WorkflowRunCreator) {
	o.CreatedBy = &v
}

// GetRevision returns the Revision field value
func (o *WorkflowRunSummaryAllOf) GetRevision() WorkflowRevisionIdentifier {
	if o == nil {
		var ret WorkflowRevisionIdentifier
		return ret
	}

	return o.Revision
}

// GetRevisionOk returns a tuple with the Revision field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunSummaryAllOf) GetRevisionOk() (*WorkflowRevisionIdentifier, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revision, true
}

// SetRevision sets field value
func (o *WorkflowRunSummaryAllOf) SetRevision(v WorkflowRevisionIdentifier) {
	o.Revision = v
}

// GetState returns the State field value
func (o *WorkflowRunSummaryAllOf) GetState() WorkflowRunStateSummary {
	if o == nil {
		var ret WorkflowRunStateSummary
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunSummaryAllOf) GetStateOk() (*WorkflowRunStateSummary, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *WorkflowRunSummaryAllOf) SetState(v WorkflowRunStateSummary) {
	o.State = v
}

func (o WorkflowRunSummaryAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CreatedBy != nil {
		toSerialize["created_by"] = o.CreatedBy
	}
	if true {
		toSerialize["revision"] = o.Revision
	}
	if true {
		toSerialize["state"] = o.State
	}
	return json.Marshal(toSerialize)
}

type NullableWorkflowRunSummaryAllOf struct {
	value *WorkflowRunSummaryAllOf
	isSet bool
}

func (v NullableWorkflowRunSummaryAllOf) Get() *WorkflowRunSummaryAllOf {
	return v.value
}

func (v *NullableWorkflowRunSummaryAllOf) Set(val *WorkflowRunSummaryAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowRunSummaryAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowRunSummaryAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowRunSummaryAllOf(val *WorkflowRunSummaryAllOf) *NullableWorkflowRunSummaryAllOf {
	return &NullableWorkflowRunSummaryAllOf{value: val, isSet: true}
}

func (v NullableWorkflowRunSummaryAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowRunSummaryAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
