/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetAccount200ResponseAllOf The response type for the current account metadata
type GetAccount200ResponseAllOf struct {
	Account *Account `json:"account,omitempty"`
}

// NewGetAccount200ResponseAllOf instantiates a new GetAccount200ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccount200ResponseAllOf() *GetAccount200ResponseAllOf {
	this := GetAccount200ResponseAllOf{}
	return &this
}

// NewGetAccount200ResponseAllOfWithDefaults instantiates a new GetAccount200ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccount200ResponseAllOfWithDefaults() *GetAccount200ResponseAllOf {
	this := GetAccount200ResponseAllOf{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *GetAccount200ResponseAllOf) GetAccount() Account {
	if o == nil || o.Account == nil {
		var ret Account
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccount200ResponseAllOf) GetAccountOk() (*Account, bool) {
	if o == nil || o.Account == nil {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *GetAccount200ResponseAllOf) HasAccount() bool {
	if o != nil && o.Account != nil {
		return true
	}

	return false
}

// SetAccount gets a reference to the given Account and assigns it to the Account field.
func (o *GetAccount200ResponseAllOf) SetAccount(v Account) {
	o.Account = &v
}

func (o GetAccount200ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Account != nil {
		toSerialize["account"] = o.Account
	}
	return json.Marshal(toSerialize)
}

type NullableGetAccount200ResponseAllOf struct {
	value *GetAccount200ResponseAllOf
	isSet bool
}

func (v NullableGetAccount200ResponseAllOf) Get() *GetAccount200ResponseAllOf {
	return v.value
}

func (v *NullableGetAccount200ResponseAllOf) Set(val *GetAccount200ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccount200ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccount200ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccount200ResponseAllOf(val *GetAccount200ResponseAllOf) *NullableGetAccount200ResponseAllOf {
	return &NullableGetAccount200ResponseAllOf{value: val, isSet: true}
}

func (v NullableGetAccount200ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccount200ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
