/*
 * Relay API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v20200615
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WorkflowRevisionSummary struct for WorkflowRevisionSummary
type WorkflowRevisionSummary struct {
	// An opaque revision identifier
	Id string `json:"id"`
}

// NewWorkflowRevisionSummary instantiates a new WorkflowRevisionSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowRevisionSummary(id string) *WorkflowRevisionSummary {
	this := WorkflowRevisionSummary{}
	this.Id = id
	return &this
}

// NewWorkflowRevisionSummaryWithDefaults instantiates a new WorkflowRevisionSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowRevisionSummaryWithDefaults() *WorkflowRevisionSummary {
	this := WorkflowRevisionSummary{}
	return &this
}

// GetId returns the Id field value
func (o *WorkflowRevisionSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WorkflowRevisionSummary) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WorkflowRevisionSummary) SetId(v string) {
	o.Id = v
}

func (o WorkflowRevisionSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableWorkflowRevisionSummary struct {
	value *WorkflowRevisionSummary
	isSet bool
}

func (v NullableWorkflowRevisionSummary) Get() *WorkflowRevisionSummary {
	return v.value
}

func (v *NullableWorkflowRevisionSummary) Set(val *WorkflowRevisionSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowRevisionSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowRevisionSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowRevisionSummary(val *WorkflowRevisionSummary) *NullableWorkflowRevisionSummary {
	return &NullableWorkflowRevisionSummary{value: val, isSet: true}
}

func (v NullableWorkflowRevisionSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowRevisionSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


