/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PlanSummary A summary of a billing plan
type PlanSummary struct {
	// Billing plan identifier
	Id string `json:"id"`
	// Visible plan name, should be unique across available plans
	Name string `json:"name"`
}

// NewPlanSummary instantiates a new PlanSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanSummary(id string, name string) *PlanSummary {
	this := PlanSummary{}
	this.Id = id
	this.Name = name
	return &this
}

// NewPlanSummaryWithDefaults instantiates a new PlanSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanSummaryWithDefaults() *PlanSummary {
	this := PlanSummary{}
	return &this
}

// GetId returns the Id field value
func (o *PlanSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlanSummary) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlanSummary) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PlanSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PlanSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PlanSummary) SetName(v string) {
	o.Name = v
}

func (o PlanSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullablePlanSummary struct {
	value *PlanSummary
	isSet bool
}

func (v NullablePlanSummary) Get() *PlanSummary {
	return v.value
}

func (v *NullablePlanSummary) Set(val *PlanSummary) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanSummary) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanSummary(val *PlanSummary) *NullablePlanSummary {
	return &NullablePlanSummary{value: val, isSet: true}
}

func (v NullablePlanSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
