/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// GetWorkflowSubscriptionsWorkflowPathParameter - struct for GetWorkflowSubscriptionsWorkflowPathParameter
type GetWorkflowSubscriptionsWorkflowPathParameter struct {
	String *string
}

// stringAsGetWorkflowSubscriptionsWorkflowPathParameter is a convenience function that returns string wrapped in GetWorkflowSubscriptionsWorkflowPathParameter
func StringAsGetWorkflowSubscriptionsWorkflowPathParameter(v *string) GetWorkflowSubscriptionsWorkflowPathParameter {
	return GetWorkflowSubscriptionsWorkflowPathParameter{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *GetWorkflowSubscriptionsWorkflowPathParameter) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into String
	err = json.Unmarshal(data, &dst.String)
	if err == nil {
		jsonstring, _ := json.Marshal(dst.String)
		if string(jsonstring) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.String = nil

		return fmt.Errorf("Data matches more than one schema in oneOf(GetWorkflowSubscriptionsWorkflowPathParameter)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("Data failed to match schemas in oneOf(GetWorkflowSubscriptionsWorkflowPathParameter)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetWorkflowSubscriptionsWorkflowPathParameter) MarshalJSON() ([]byte, error) {
	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *GetWorkflowSubscriptionsWorkflowPathParameter) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableGetWorkflowSubscriptionsWorkflowPathParameter struct {
	value *GetWorkflowSubscriptionsWorkflowPathParameter
	isSet bool
}

func (v NullableGetWorkflowSubscriptionsWorkflowPathParameter) Get() *GetWorkflowSubscriptionsWorkflowPathParameter {
	return v.value
}

func (v *NullableGetWorkflowSubscriptionsWorkflowPathParameter) Set(val *GetWorkflowSubscriptionsWorkflowPathParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWorkflowSubscriptionsWorkflowPathParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWorkflowSubscriptionsWorkflowPathParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWorkflowSubscriptionsWorkflowPathParameter(val *GetWorkflowSubscriptionsWorkflowPathParameter) *NullableGetWorkflowSubscriptionsWorkflowPathParameter {
	return &NullableGetWorkflowSubscriptionsWorkflowPathParameter{value: val, isSet: true}
}

func (v NullableGetWorkflowSubscriptionsWorkflowPathParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWorkflowSubscriptionsWorkflowPathParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
