/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// AcceptAccountTerms200Response struct for AcceptAccountTerms200Response
type AcceptAccountTerms200Response struct {
	Access        *EntityAccess  `json:"access,omitempty"`
	AcceptedTerms *AcceptedTerms `json:"accepted_terms,omitempty"`
}

// NewAcceptAccountTerms200Response instantiates a new AcceptAccountTerms200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAcceptAccountTerms200Response() *AcceptAccountTerms200Response {
	this := AcceptAccountTerms200Response{}
	return &this
}

// NewAcceptAccountTerms200ResponseWithDefaults instantiates a new AcceptAccountTerms200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAcceptAccountTerms200ResponseWithDefaults() *AcceptAccountTerms200Response {
	this := AcceptAccountTerms200Response{}
	return &this
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *AcceptAccountTerms200Response) GetAccess() EntityAccess {
	if o == nil || o.Access == nil {
		var ret EntityAccess
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AcceptAccountTerms200Response) GetAccessOk() (*EntityAccess, bool) {
	if o == nil || o.Access == nil {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *AcceptAccountTerms200Response) HasAccess() bool {
	if o != nil && o.Access != nil {
		return true
	}

	return false
}

// SetAccess gets a reference to the given EntityAccess and assigns it to the Access field.
func (o *AcceptAccountTerms200Response) SetAccess(v EntityAccess) {
	o.Access = &v
}

// GetAcceptedTerms returns the AcceptedTerms field value if set, zero value otherwise.
func (o *AcceptAccountTerms200Response) GetAcceptedTerms() AcceptedTerms {
	if o == nil || o.AcceptedTerms == nil {
		var ret AcceptedTerms
		return ret
	}
	return *o.AcceptedTerms
}

// GetAcceptedTermsOk returns a tuple with the AcceptedTerms field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AcceptAccountTerms200Response) GetAcceptedTermsOk() (*AcceptedTerms, bool) {
	if o == nil || o.AcceptedTerms == nil {
		return nil, false
	}
	return o.AcceptedTerms, true
}

// HasAcceptedTerms returns a boolean if a field has been set.
func (o *AcceptAccountTerms200Response) HasAcceptedTerms() bool {
	if o != nil && o.AcceptedTerms != nil {
		return true
	}

	return false
}

// SetAcceptedTerms gets a reference to the given AcceptedTerms and assigns it to the AcceptedTerms field.
func (o *AcceptAccountTerms200Response) SetAcceptedTerms(v AcceptedTerms) {
	o.AcceptedTerms = &v
}

func (o AcceptAccountTerms200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Access != nil {
		toSerialize["access"] = o.Access
	}
	if o.AcceptedTerms != nil {
		toSerialize["accepted_terms"] = o.AcceptedTerms
	}
	return json.Marshal(toSerialize)
}

type NullableAcceptAccountTerms200Response struct {
	value *AcceptAccountTerms200Response
	isSet bool
}

func (v NullableAcceptAccountTerms200Response) Get() *AcceptAccountTerms200Response {
	return v.value
}

func (v *NullableAcceptAccountTerms200Response) Set(val *AcceptAccountTerms200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableAcceptAccountTerms200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableAcceptAccountTerms200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAcceptAccountTerms200Response(val *AcceptAccountTerms200Response) *NullableAcceptAccountTerms200Response {
	return &NullableAcceptAccountTerms200Response{value: val, isSet: true}
}

func (v NullableAcceptAccountTerms200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAcceptAccountTerms200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
