/*
 * Relay API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v20200615
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ConnectionSummary struct for ConnectionSummary
type ConnectionSummary struct {
	// The unique ID of this connection
	Id string `json:"id"`
	// A descriptive connection name
	Name string `json:"name"`
	// This connection's type identifier
	Type string `json:"type"`
	// The set of capabilities to enable for a connection
	Capabilities []ConnectionProviderCapability `json:"capabilities"`
}

// NewConnectionSummary instantiates a new ConnectionSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectionSummary(id string, name string, type_ string, capabilities []ConnectionProviderCapability) *ConnectionSummary {
	this := ConnectionSummary{}
	this.Id = id
	this.Name = name
	this.Type = type_
	this.Capabilities = capabilities
	return &this
}

// NewConnectionSummaryWithDefaults instantiates a new ConnectionSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectionSummaryWithDefaults() *ConnectionSummary {
	this := ConnectionSummary{}
	return &this
}

// GetId returns the Id field value
func (o *ConnectionSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ConnectionSummary) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ConnectionSummary) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ConnectionSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ConnectionSummary) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ConnectionSummary) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *ConnectionSummary) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ConnectionSummary) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ConnectionSummary) SetType(v string) {
	o.Type = v
}

// GetCapabilities returns the Capabilities field value
func (o *ConnectionSummary) GetCapabilities() []ConnectionProviderCapability {
	if o == nil {
		var ret []ConnectionProviderCapability
		return ret
	}

	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value
// and a boolean to check if the value has been set.
func (o *ConnectionSummary) GetCapabilitiesOk() (*[]ConnectionProviderCapability, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Capabilities, true
}

// SetCapabilities sets field value
func (o *ConnectionSummary) SetCapabilities(v []ConnectionProviderCapability) {
	o.Capabilities = v
}

func (o ConnectionSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["capabilities"] = o.Capabilities
	}
	return json.Marshal(toSerialize)
}

type NullableConnectionSummary struct {
	value *ConnectionSummary
	isSet bool
}

func (v NullableConnectionSummary) Get() *ConnectionSummary {
	return v.value
}

func (v *NullableConnectionSummary) Set(val *ConnectionSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectionSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectionSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectionSummary(val *ConnectionSummary) *NullableConnectionSummary {
	return &NullableConnectionSummary{value: val, isSet: true}
}

func (v NullableConnectionSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectionSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


