/*
 * Relay API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v20200615
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// ApprovalWorkflowRunStepStateAllOf State representation of an approval step
type ApprovalWorkflowRunStepStateAllOf struct {
	// Workflow run step approval for manual gates
	Approval *string `json:"approval,omitempty"`
	// Time at which the step was approved or rejected
	ApprovalSubmittedAt NullableTime `json:"approval_submitted_at,omitempty"`
	Approver *UserSummary `json:"approver,omitempty"`
	// Type of step
	Type string `json:"type"`
}

// NewApprovalWorkflowRunStepStateAllOf instantiates a new ApprovalWorkflowRunStepStateAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprovalWorkflowRunStepStateAllOf(type_ string) *ApprovalWorkflowRunStepStateAllOf {
	this := ApprovalWorkflowRunStepStateAllOf{}
	var approval string = "waiting"
	this.Approval = &approval
	this.Type = type_
	return &this
}

// NewApprovalWorkflowRunStepStateAllOfWithDefaults instantiates a new ApprovalWorkflowRunStepStateAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApprovalWorkflowRunStepStateAllOfWithDefaults() *ApprovalWorkflowRunStepStateAllOf {
	this := ApprovalWorkflowRunStepStateAllOf{}
	var approval string = "waiting"
	this.Approval = &approval
	return &this
}

// GetApproval returns the Approval field value if set, zero value otherwise.
func (o *ApprovalWorkflowRunStepStateAllOf) GetApproval() string {
	if o == nil || o.Approval == nil {
		var ret string
		return ret
	}
	return *o.Approval
}

// GetApprovalOk returns a tuple with the Approval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflowRunStepStateAllOf) GetApprovalOk() (*string, bool) {
	if o == nil || o.Approval == nil {
		return nil, false
	}
	return o.Approval, true
}

// HasApproval returns a boolean if a field has been set.
func (o *ApprovalWorkflowRunStepStateAllOf) HasApproval() bool {
	if o != nil && o.Approval != nil {
		return true
	}

	return false
}

// SetApproval gets a reference to the given string and assigns it to the Approval field.
func (o *ApprovalWorkflowRunStepStateAllOf) SetApproval(v string) {
	o.Approval = &v
}

// GetApprovalSubmittedAt returns the ApprovalSubmittedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApprovalWorkflowRunStepStateAllOf) GetApprovalSubmittedAt() time.Time {
	if o == nil || o.ApprovalSubmittedAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.ApprovalSubmittedAt.Get()
}

// GetApprovalSubmittedAtOk returns a tuple with the ApprovalSubmittedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApprovalWorkflowRunStepStateAllOf) GetApprovalSubmittedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ApprovalSubmittedAt.Get(), o.ApprovalSubmittedAt.IsSet()
}

// HasApprovalSubmittedAt returns a boolean if a field has been set.
func (o *ApprovalWorkflowRunStepStateAllOf) HasApprovalSubmittedAt() bool {
	if o != nil && o.ApprovalSubmittedAt.IsSet() {
		return true
	}

	return false
}

// SetApprovalSubmittedAt gets a reference to the given NullableTime and assigns it to the ApprovalSubmittedAt field.
func (o *ApprovalWorkflowRunStepStateAllOf) SetApprovalSubmittedAt(v time.Time) {
	o.ApprovalSubmittedAt.Set(&v)
}
// SetApprovalSubmittedAtNil sets the value for ApprovalSubmittedAt to be an explicit nil
func (o *ApprovalWorkflowRunStepStateAllOf) SetApprovalSubmittedAtNil() {
	o.ApprovalSubmittedAt.Set(nil)
}

// UnsetApprovalSubmittedAt ensures that no value is present for ApprovalSubmittedAt, not even an explicit nil
func (o *ApprovalWorkflowRunStepStateAllOf) UnsetApprovalSubmittedAt() {
	o.ApprovalSubmittedAt.Unset()
}

// GetApprover returns the Approver field value if set, zero value otherwise.
func (o *ApprovalWorkflowRunStepStateAllOf) GetApprover() UserSummary {
	if o == nil || o.Approver == nil {
		var ret UserSummary
		return ret
	}
	return *o.Approver
}

// GetApproverOk returns a tuple with the Approver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflowRunStepStateAllOf) GetApproverOk() (*UserSummary, bool) {
	if o == nil || o.Approver == nil {
		return nil, false
	}
	return o.Approver, true
}

// HasApprover returns a boolean if a field has been set.
func (o *ApprovalWorkflowRunStepStateAllOf) HasApprover() bool {
	if o != nil && o.Approver != nil {
		return true
	}

	return false
}

// SetApprover gets a reference to the given UserSummary and assigns it to the Approver field.
func (o *ApprovalWorkflowRunStepStateAllOf) SetApprover(v UserSummary) {
	o.Approver = &v
}

// GetType returns the Type field value
func (o *ApprovalWorkflowRunStepStateAllOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflowRunStepStateAllOf) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApprovalWorkflowRunStepStateAllOf) SetType(v string) {
	o.Type = v
}

func (o ApprovalWorkflowRunStepStateAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Approval != nil {
		toSerialize["approval"] = o.Approval
	}
	if o.ApprovalSubmittedAt.IsSet() {
		toSerialize["approval_submitted_at"] = o.ApprovalSubmittedAt.Get()
	}
	if o.Approver != nil {
		toSerialize["approver"] = o.Approver
	}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableApprovalWorkflowRunStepStateAllOf struct {
	value *ApprovalWorkflowRunStepStateAllOf
	isSet bool
}

func (v NullableApprovalWorkflowRunStepStateAllOf) Get() *ApprovalWorkflowRunStepStateAllOf {
	return v.value
}

func (v *NullableApprovalWorkflowRunStepStateAllOf) Set(val *ApprovalWorkflowRunStepStateAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovalWorkflowRunStepStateAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovalWorkflowRunStepStateAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovalWorkflowRunStepStateAllOf(val *ApprovalWorkflowRunStepStateAllOf) *NullableApprovalWorkflowRunStepStateAllOf {
	return &NullableApprovalWorkflowRunStepStateAllOf{value: val, isSet: true}
}

func (v NullableApprovalWorkflowRunStepStateAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovalWorkflowRunStepStateAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


