/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WorkflowRunIdentifier A unique identifier for a workflow run
type WorkflowRunIdentifier struct {
	// The sequential identifier for a single workflow run
	RunNumber int32              `json:"run_number"`
	Workflow  WorkflowIdentifier `json:"workflow"`
}

// NewWorkflowRunIdentifier instantiates a new WorkflowRunIdentifier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowRunIdentifier(runNumber int32, workflow WorkflowIdentifier) *WorkflowRunIdentifier {
	this := WorkflowRunIdentifier{}
	this.RunNumber = runNumber
	this.Workflow = workflow
	return &this
}

// NewWorkflowRunIdentifierWithDefaults instantiates a new WorkflowRunIdentifier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowRunIdentifierWithDefaults() *WorkflowRunIdentifier {
	this := WorkflowRunIdentifier{}
	return &this
}

// GetRunNumber returns the RunNumber field value
func (o *WorkflowRunIdentifier) GetRunNumber() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RunNumber
}

// GetRunNumberOk returns a tuple with the RunNumber field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunIdentifier) GetRunNumberOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunNumber, true
}

// SetRunNumber sets field value
func (o *WorkflowRunIdentifier) SetRunNumber(v int32) {
	o.RunNumber = v
}

// GetWorkflow returns the Workflow field value
func (o *WorkflowRunIdentifier) GetWorkflow() WorkflowIdentifier {
	if o == nil {
		var ret WorkflowIdentifier
		return ret
	}

	return o.Workflow
}

// GetWorkflowOk returns a tuple with the Workflow field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunIdentifier) GetWorkflowOk() (*WorkflowIdentifier, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Workflow, true
}

// SetWorkflow sets field value
func (o *WorkflowRunIdentifier) SetWorkflow(v WorkflowIdentifier) {
	o.Workflow = v
}

func (o WorkflowRunIdentifier) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["run_number"] = o.RunNumber
	}
	if true {
		toSerialize["workflow"] = o.Workflow
	}
	return json.Marshal(toSerialize)
}

type NullableWorkflowRunIdentifier struct {
	value *WorkflowRunIdentifier
	isSet bool
}

func (v NullableWorkflowRunIdentifier) Get() *WorkflowRunIdentifier {
	return v.value
}

func (v *NullableWorkflowRunIdentifier) Set(val *WorkflowRunIdentifier) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowRunIdentifier) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowRunIdentifier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowRunIdentifier(val *WorkflowRunIdentifier) *NullableWorkflowRunIdentifier {
	return &NullableWorkflowRunIdentifier{value: val, isSet: true}
}

func (v NullableWorkflowRunIdentifier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowRunIdentifier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
