/*
 * Relay API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v20200615
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// WorkflowRunState struct for WorkflowRunState
type WorkflowRunState struct {
	// Time at which the workflow execution ended
	EndedAt NullableTime `json:"ended_at"`
	// Time at which workflow execution started
	StartedAt NullableTime `json:"started_at"`
	// Current status of the workflow, based on steps statuses and approvals
	Status string `json:"status"`
	// Status of individual run steps, indexed by name
	Steps *map[string]WorkflowRunStepState `json:"steps,omitempty"`
}

// NewWorkflowRunState instantiates a new WorkflowRunState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowRunState(endedAt NullableTime, startedAt NullableTime, status string) *WorkflowRunState {
	this := WorkflowRunState{}
	this.EndedAt = endedAt
	this.StartedAt = startedAt
	this.Status = status
	return &this
}

// NewWorkflowRunStateWithDefaults instantiates a new WorkflowRunState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowRunStateWithDefaults() *WorkflowRunState {
	this := WorkflowRunState{}
	return &this
}

// GetEndedAt returns the EndedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *WorkflowRunState) GetEndedAt() time.Time {
	if o == nil || o.EndedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.EndedAt.Get()
}

// GetEndedAtOk returns a tuple with the EndedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowRunState) GetEndedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.EndedAt.Get(), o.EndedAt.IsSet()
}

// SetEndedAt sets field value
func (o *WorkflowRunState) SetEndedAt(v time.Time) {
	o.EndedAt.Set(&v)
}

// GetStartedAt returns the StartedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *WorkflowRunState) GetStartedAt() time.Time {
	if o == nil || o.StartedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.StartedAt.Get()
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WorkflowRunState) GetStartedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.StartedAt.Get(), o.StartedAt.IsSet()
}

// SetStartedAt sets field value
func (o *WorkflowRunState) SetStartedAt(v time.Time) {
	o.StartedAt.Set(&v)
}

// GetStatus returns the Status field value
func (o *WorkflowRunState) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunState) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *WorkflowRunState) SetStatus(v string) {
	o.Status = v
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *WorkflowRunState) GetSteps() map[string]WorkflowRunStepState {
	if o == nil || o.Steps == nil {
		var ret map[string]WorkflowRunStepState
		return ret
	}
	return *o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkflowRunState) GetStepsOk() (*map[string]WorkflowRunStepState, bool) {
	if o == nil || o.Steps == nil {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *WorkflowRunState) HasSteps() bool {
	if o != nil && o.Steps != nil {
		return true
	}

	return false
}

// SetSteps gets a reference to the given map[string]WorkflowRunStepState and assigns it to the Steps field.
func (o *WorkflowRunState) SetSteps(v map[string]WorkflowRunStepState) {
	o.Steps = &v
}

func (o WorkflowRunState) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ended_at"] = o.EndedAt.Get()
	}
	if true {
		toSerialize["started_at"] = o.StartedAt.Get()
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.Steps != nil {
		toSerialize["steps"] = o.Steps
	}
	return json.Marshal(toSerialize)
}

type NullableWorkflowRunState struct {
	value *WorkflowRunState
	isSet bool
}

func (v NullableWorkflowRunState) Get() *WorkflowRunState {
	return v.value
}

func (v *NullableWorkflowRunState) Set(val *WorkflowRunState) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowRunState) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowRunState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowRunState(val *WorkflowRunState) *NullableWorkflowRunState {
	return &NullableWorkflowRunState{value: val, isSet: true}
}

func (v NullableWorkflowRunState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowRunState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


