/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EntitlementPlanAllOf struct for EntitlementPlanAllOf
type EntitlementPlanAllOf struct {
	// Whether or not this plan is available to users
	Available bool `json:"available"`
	// Pricing models associated with this plan
	Prices []EntitlementPlanPrice `json:"prices"`
}

// NewEntitlementPlanAllOf instantiates a new EntitlementPlanAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitlementPlanAllOf(available bool, prices []EntitlementPlanPrice) *EntitlementPlanAllOf {
	this := EntitlementPlanAllOf{}
	this.Available = available
	this.Prices = prices
	return &this
}

// NewEntitlementPlanAllOfWithDefaults instantiates a new EntitlementPlanAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitlementPlanAllOfWithDefaults() *EntitlementPlanAllOf {
	this := EntitlementPlanAllOf{}
	return &this
}

// GetAvailable returns the Available field value
func (o *EntitlementPlanAllOf) GetAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *EntitlementPlanAllOf) GetAvailableOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Available, true
}

// SetAvailable sets field value
func (o *EntitlementPlanAllOf) SetAvailable(v bool) {
	o.Available = v
}

// GetPrices returns the Prices field value
func (o *EntitlementPlanAllOf) GetPrices() []EntitlementPlanPrice {
	if o == nil {
		var ret []EntitlementPlanPrice
		return ret
	}

	return o.Prices
}

// GetPricesOk returns a tuple with the Prices field value
// and a boolean to check if the value has been set.
func (o *EntitlementPlanAllOf) GetPricesOk() ([]EntitlementPlanPrice, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prices, true
}

// SetPrices sets field value
func (o *EntitlementPlanAllOf) SetPrices(v []EntitlementPlanPrice) {
	o.Prices = v
}

func (o EntitlementPlanAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["available"] = o.Available
	}
	if true {
		toSerialize["prices"] = o.Prices
	}
	return json.Marshal(toSerialize)
}

type NullableEntitlementPlanAllOf struct {
	value *EntitlementPlanAllOf
	isSet bool
}

func (v NullableEntitlementPlanAllOf) Get() *EntitlementPlanAllOf {
	return v.value
}

func (v *NullableEntitlementPlanAllOf) Set(val *EntitlementPlanAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitlementPlanAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitlementPlanAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitlementPlanAllOf(val *EntitlementPlanAllOf) *NullableEntitlementPlanAllOf {
	return &NullableEntitlementPlanAllOf{value: val, isSet: true}
}

func (v NullableEntitlementPlanAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitlementPlanAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
