/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// GetWorkflowTriggers200Response The response type for retrieving the list of workflow triggers
type GetWorkflowTriggers200Response struct {
	// A list of workflow triggers
	Triggers []WorkflowTriggerComposite `json:"triggers,omitempty"`
}

// NewGetWorkflowTriggers200Response instantiates a new GetWorkflowTriggers200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWorkflowTriggers200Response() *GetWorkflowTriggers200Response {
	this := GetWorkflowTriggers200Response{}
	return &this
}

// NewGetWorkflowTriggers200ResponseWithDefaults instantiates a new GetWorkflowTriggers200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWorkflowTriggers200ResponseWithDefaults() *GetWorkflowTriggers200Response {
	this := GetWorkflowTriggers200Response{}
	return &this
}

// GetTriggers returns the Triggers field value if set, zero value otherwise.
func (o *GetWorkflowTriggers200Response) GetTriggers() []WorkflowTriggerComposite {
	if o == nil || o.Triggers == nil {
		var ret []WorkflowTriggerComposite
		return ret
	}
	return o.Triggers
}

// GetTriggersOk returns a tuple with the Triggers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWorkflowTriggers200Response) GetTriggersOk() ([]WorkflowTriggerComposite, bool) {
	if o == nil || o.Triggers == nil {
		return nil, false
	}
	return o.Triggers, true
}

// HasTriggers returns a boolean if a field has been set.
func (o *GetWorkflowTriggers200Response) HasTriggers() bool {
	if o != nil && o.Triggers != nil {
		return true
	}

	return false
}

// SetTriggers gets a reference to the given []WorkflowTriggerComposite and assigns it to the Triggers field.
func (o *GetWorkflowTriggers200Response) SetTriggers(v []WorkflowTriggerComposite) {
	o.Triggers = v
}

func (o GetWorkflowTriggers200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Triggers != nil {
		toSerialize["triggers"] = o.Triggers
	}
	return json.Marshal(toSerialize)
}

type NullableGetWorkflowTriggers200Response struct {
	value *GetWorkflowTriggers200Response
	isSet bool
}

func (v NullableGetWorkflowTriggers200Response) Get() *GetWorkflowTriggers200Response {
	return v.value
}

func (v *NullableGetWorkflowTriggers200Response) Set(val *GetWorkflowTriggers200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWorkflowTriggers200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWorkflowTriggers200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWorkflowTriggers200Response(val *GetWorkflowTriggers200Response) *NullableGetWorkflowTriggers200Response {
	return &NullableGetWorkflowTriggers200Response{value: val, isSet: true}
}

func (v NullableGetWorkflowTriggers200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWorkflowTriggers200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
