/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateWorkflowSecret201Response struct for CreateWorkflowSecret201Response
type CreateWorkflowSecret201Response struct {
	Access *EntityAccess          `json:"access,omitempty"`
	Secret *WorkflowSecretSummary `json:"secret,omitempty"`
}

// NewCreateWorkflowSecret201Response instantiates a new CreateWorkflowSecret201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWorkflowSecret201Response() *CreateWorkflowSecret201Response {
	this := CreateWorkflowSecret201Response{}
	return &this
}

// NewCreateWorkflowSecret201ResponseWithDefaults instantiates a new CreateWorkflowSecret201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWorkflowSecret201ResponseWithDefaults() *CreateWorkflowSecret201Response {
	this := CreateWorkflowSecret201Response{}
	return &this
}

// GetAccess returns the Access field value if set, zero value otherwise.
func (o *CreateWorkflowSecret201Response) GetAccess() EntityAccess {
	if o == nil || o.Access == nil {
		var ret EntityAccess
		return ret
	}
	return *o.Access
}

// GetAccessOk returns a tuple with the Access field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkflowSecret201Response) GetAccessOk() (*EntityAccess, bool) {
	if o == nil || o.Access == nil {
		return nil, false
	}
	return o.Access, true
}

// HasAccess returns a boolean if a field has been set.
func (o *CreateWorkflowSecret201Response) HasAccess() bool {
	if o != nil && o.Access != nil {
		return true
	}

	return false
}

// SetAccess gets a reference to the given EntityAccess and assigns it to the Access field.
func (o *CreateWorkflowSecret201Response) SetAccess(v EntityAccess) {
	o.Access = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *CreateWorkflowSecret201Response) GetSecret() WorkflowSecretSummary {
	if o == nil || o.Secret == nil {
		var ret WorkflowSecretSummary
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWorkflowSecret201Response) GetSecretOk() (*WorkflowSecretSummary, bool) {
	if o == nil || o.Secret == nil {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *CreateWorkflowSecret201Response) HasSecret() bool {
	if o != nil && o.Secret != nil {
		return true
	}

	return false
}

// SetSecret gets a reference to the given WorkflowSecretSummary and assigns it to the Secret field.
func (o *CreateWorkflowSecret201Response) SetSecret(v WorkflowSecretSummary) {
	o.Secret = &v
}

func (o CreateWorkflowSecret201Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Access != nil {
		toSerialize["access"] = o.Access
	}
	if o.Secret != nil {
		toSerialize["secret"] = o.Secret
	}
	return json.Marshal(toSerialize)
}

type NullableCreateWorkflowSecret201Response struct {
	value *CreateWorkflowSecret201Response
	isSet bool
}

func (v NullableCreateWorkflowSecret201Response) Get() *CreateWorkflowSecret201Response {
	return v.value
}

func (v *NullableCreateWorkflowSecret201Response) Set(val *CreateWorkflowSecret201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWorkflowSecret201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWorkflowSecret201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWorkflowSecret201Response(val *CreateWorkflowSecret201Response) *NullableCreateWorkflowSecret201Response {
	return &NullableCreateWorkflowSecret201Response{value: val, isSet: true}
}

func (v NullableCreateWorkflowSecret201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateWorkflowSecret201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
