/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateFolder201ResponseAllOf The response type for creating a folder
type CreateFolder201ResponseAllOf struct {
	Folder *Folder `json:"folder,omitempty"`
}

// NewCreateFolder201ResponseAllOf instantiates a new CreateFolder201ResponseAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateFolder201ResponseAllOf() *CreateFolder201ResponseAllOf {
	this := CreateFolder201ResponseAllOf{}
	return &this
}

// NewCreateFolder201ResponseAllOfWithDefaults instantiates a new CreateFolder201ResponseAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateFolder201ResponseAllOfWithDefaults() *CreateFolder201ResponseAllOf {
	this := CreateFolder201ResponseAllOf{}
	return &this
}

// GetFolder returns the Folder field value if set, zero value otherwise.
func (o *CreateFolder201ResponseAllOf) GetFolder() Folder {
	if o == nil || o.Folder == nil {
		var ret Folder
		return ret
	}
	return *o.Folder
}

// GetFolderOk returns a tuple with the Folder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateFolder201ResponseAllOf) GetFolderOk() (*Folder, bool) {
	if o == nil || o.Folder == nil {
		return nil, false
	}
	return o.Folder, true
}

// HasFolder returns a boolean if a field has been set.
func (o *CreateFolder201ResponseAllOf) HasFolder() bool {
	if o != nil && o.Folder != nil {
		return true
	}

	return false
}

// SetFolder gets a reference to the given Folder and assigns it to the Folder field.
func (o *CreateFolder201ResponseAllOf) SetFolder(v Folder) {
	o.Folder = &v
}

func (o CreateFolder201ResponseAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Folder != nil {
		toSerialize["folder"] = o.Folder
	}
	return json.Marshal(toSerialize)
}

type NullableCreateFolder201ResponseAllOf struct {
	value *CreateFolder201ResponseAllOf
	isSet bool
}

func (v NullableCreateFolder201ResponseAllOf) Get() *CreateFolder201ResponseAllOf {
	return v.value
}

func (v *NullableCreateFolder201ResponseAllOf) Set(val *CreateFolder201ResponseAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateFolder201ResponseAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateFolder201ResponseAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateFolder201ResponseAllOf(val *CreateFolder201ResponseAllOf) *NullableCreateFolder201ResponseAllOf {
	return &NullableCreateFolder201ResponseAllOf{value: val, isSet: true}
}

func (v NullableCreateFolder201ResponseAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateFolder201ResponseAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
