/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// WorkflowRunStepDecoratorLinkLink Link is a link-type decorator.
type WorkflowRunStepDecoratorLinkLink struct {
	// Describes what the URI points to.
	Description string `json:"description"`
	// A URI for the decorator
	Uri string `json:"uri"`
}

// NewWorkflowRunStepDecoratorLinkLink instantiates a new WorkflowRunStepDecoratorLinkLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkflowRunStepDecoratorLinkLink(description string, uri string) *WorkflowRunStepDecoratorLinkLink {
	this := WorkflowRunStepDecoratorLinkLink{}
	this.Description = description
	this.Uri = uri
	return &this
}

// NewWorkflowRunStepDecoratorLinkLinkWithDefaults instantiates a new WorkflowRunStepDecoratorLinkLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkflowRunStepDecoratorLinkLinkWithDefaults() *WorkflowRunStepDecoratorLinkLink {
	this := WorkflowRunStepDecoratorLinkLink{}
	return &this
}

// GetDescription returns the Description field value
func (o *WorkflowRunStepDecoratorLinkLink) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunStepDecoratorLinkLink) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *WorkflowRunStepDecoratorLinkLink) SetDescription(v string) {
	o.Description = v
}

// GetUri returns the Uri field value
func (o *WorkflowRunStepDecoratorLinkLink) GetUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uri
}

// GetUriOk returns a tuple with the Uri field value
// and a boolean to check if the value has been set.
func (o *WorkflowRunStepDecoratorLinkLink) GetUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uri, true
}

// SetUri sets field value
func (o *WorkflowRunStepDecoratorLinkLink) SetUri(v string) {
	o.Uri = v
}

func (o WorkflowRunStepDecoratorLinkLink) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["uri"] = o.Uri
	}
	return json.Marshal(toSerialize)
}

type NullableWorkflowRunStepDecoratorLinkLink struct {
	value *WorkflowRunStepDecoratorLinkLink
	isSet bool
}

func (v NullableWorkflowRunStepDecoratorLinkLink) Get() *WorkflowRunStepDecoratorLinkLink {
	return v.value
}

func (v *NullableWorkflowRunStepDecoratorLinkLink) Set(val *WorkflowRunStepDecoratorLinkLink) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkflowRunStepDecoratorLinkLink) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkflowRunStepDecoratorLinkLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkflowRunStepDecoratorLinkLink(val *WorkflowRunStepDecoratorLinkLink) *NullableWorkflowRunStepDecoratorLinkLink {
	return &NullableWorkflowRunStepDecoratorLinkLink{value: val, isSet: true}
}

func (v NullableWorkflowRunStepDecoratorLinkLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkflowRunStepDecoratorLinkLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
