/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// EntitlementPlanPriceSummary A summary of a product entitlement plan pricing model
type EntitlementPlanPriceSummary struct {
	// Visible plan price name
	Name string `json:"name"`
	// Unique plan price identifier
	Slug string `json:"slug"`
}

// NewEntitlementPlanPriceSummary instantiates a new EntitlementPlanPriceSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntitlementPlanPriceSummary(name string, slug string) *EntitlementPlanPriceSummary {
	this := EntitlementPlanPriceSummary{}
	this.Name = name
	this.Slug = slug
	return &this
}

// NewEntitlementPlanPriceSummaryWithDefaults instantiates a new EntitlementPlanPriceSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntitlementPlanPriceSummaryWithDefaults() *EntitlementPlanPriceSummary {
	this := EntitlementPlanPriceSummary{}
	return &this
}

// GetName returns the Name field value
func (o *EntitlementPlanPriceSummary) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EntitlementPlanPriceSummary) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EntitlementPlanPriceSummary) SetName(v string) {
	o.Name = v
}

// GetSlug returns the Slug field value
func (o *EntitlementPlanPriceSummary) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *EntitlementPlanPriceSummary) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *EntitlementPlanPriceSummary) SetSlug(v string) {
	o.Slug = v
}

func (o EntitlementPlanPriceSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["slug"] = o.Slug
	}
	return json.Marshal(toSerialize)
}

type NullableEntitlementPlanPriceSummary struct {
	value *EntitlementPlanPriceSummary
	isSet bool
}

func (v NullableEntitlementPlanPriceSummary) Get() *EntitlementPlanPriceSummary {
	return v.value
}

func (v *NullableEntitlementPlanPriceSummary) Set(val *EntitlementPlanPriceSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableEntitlementPlanPriceSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableEntitlementPlanPriceSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntitlementPlanPriceSummary(val *EntitlementPlanPriceSummary) *NullableEntitlementPlanPriceSummary {
	return &NullableEntitlementPlanPriceSummary{value: val, isSet: true}
}

func (v NullableEntitlementPlanPriceSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntitlementPlanPriceSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
