/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// StartConnectionProviderOAuth2Auth200Response The response type for initiating an OAuth 2.0 connection flow
type StartConnectionProviderOAuth2Auth200Response struct {
	// The URL to forward the user to
	Url string `json:"url"`
}

// NewStartConnectionProviderOAuth2Auth200Response instantiates a new StartConnectionProviderOAuth2Auth200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartConnectionProviderOAuth2Auth200Response(url string) *StartConnectionProviderOAuth2Auth200Response {
	this := StartConnectionProviderOAuth2Auth200Response{}
	this.Url = url
	return &this
}

// NewStartConnectionProviderOAuth2Auth200ResponseWithDefaults instantiates a new StartConnectionProviderOAuth2Auth200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartConnectionProviderOAuth2Auth200ResponseWithDefaults() *StartConnectionProviderOAuth2Auth200Response {
	this := StartConnectionProviderOAuth2Auth200Response{}
	return &this
}

// GetUrl returns the Url field value
func (o *StartConnectionProviderOAuth2Auth200Response) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *StartConnectionProviderOAuth2Auth200Response) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *StartConnectionProviderOAuth2Auth200Response) SetUrl(v string) {
	o.Url = v
}

func (o StartConnectionProviderOAuth2Auth200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["url"] = o.Url
	}
	return json.Marshal(toSerialize)
}

type NullableStartConnectionProviderOAuth2Auth200Response struct {
	value *StartConnectionProviderOAuth2Auth200Response
	isSet bool
}

func (v NullableStartConnectionProviderOAuth2Auth200Response) Get() *StartConnectionProviderOAuth2Auth200Response {
	return v.value
}

func (v *NullableStartConnectionProviderOAuth2Auth200Response) Set(val *StartConnectionProviderOAuth2Auth200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableStartConnectionProviderOAuth2Auth200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableStartConnectionProviderOAuth2Auth200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartConnectionProviderOAuth2Auth200Response(val *StartConnectionProviderOAuth2Auth200Response) *NullableStartConnectionProviderOAuth2Auth200Response {
	return &NullableStartConnectionProviderOAuth2Auth200Response{value: val, isSet: true}
}

func (v NullableStartConnectionProviderOAuth2Auth200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartConnectionProviderOAuth2Auth200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
