/*
Relay API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v20200615
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ContainerWorkflowRunStepState State representation of a container step
type ContainerWorkflowRunStepState struct {
	// Type of step
	Type string `json:"type"`
}

// NewContainerWorkflowRunStepState instantiates a new ContainerWorkflowRunStepState object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerWorkflowRunStepState(type_ string) *ContainerWorkflowRunStepState {
	this := ContainerWorkflowRunStepState{}
	this.Type = type_
	return &this
}

// NewContainerWorkflowRunStepStateWithDefaults instantiates a new ContainerWorkflowRunStepState object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerWorkflowRunStepStateWithDefaults() *ContainerWorkflowRunStepState {
	this := ContainerWorkflowRunStepState{}
	return &this
}

// GetType returns the Type field value
func (o *ContainerWorkflowRunStepState) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ContainerWorkflowRunStepState) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ContainerWorkflowRunStepState) SetType(v string) {
	o.Type = v
}

func (o ContainerWorkflowRunStepState) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableContainerWorkflowRunStepState struct {
	value *ContainerWorkflowRunStepState
	isSet bool
}

func (v NullableContainerWorkflowRunStepState) Get() *ContainerWorkflowRunStepState {
	return v.value
}

func (v *NullableContainerWorkflowRunStepState) Set(val *ContainerWorkflowRunStepState) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerWorkflowRunStepState) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerWorkflowRunStepState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerWorkflowRunStepState(val *ContainerWorkflowRunStepState) *NullableContainerWorkflowRunStepState {
	return &NullableContainerWorkflowRunStepState{value: val, isSet: true}
}

func (v NullableContainerWorkflowRunStepState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerWorkflowRunStepState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
