name: Models CI
on:
  push:
    paths:
    - models/**
  pull_request:
    paths:
    - models/**
defaults:
  run:
    working-directory: models
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/go/pkg/sumdb
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Check
      run: |
        go run github.com/golangci/golangci-lint/cmd/golangci-lint run --timeout 10m
        go generate ./...
        if [ -n "$(git status --porcelain --untracked-files=no)" ]; then
          exit 1
        fi
